services:
  - type: web
    name: alumni-api
    runtime: node
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_BASE_URL
        sync: false

  - type: static_site
    name: alumni-frontend
    rootDir: client
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        sync: false